dist: trusty
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=formatting
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37

install:
  - ./scripts/install

script:
  - ./scripts/run tox

deploy:
  provider: pypi
  user: bedmondmark
  password: ...
  on:
    branch: master
    tags: true
  distributions: "sdist bdist_wheel"
