dist: trusty
sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37

install:
  - ./scripts/install

script:
  - ./scripts/run tox