dist: trusty
sudo: false

jobs:
  include:
  - stage: test
    language: python
    matrix:
      include:
      - python: 3.6
        env: TOXENV=formatting
      - python: 3.4
        env: TOXENV=py34
      - python: 3.5
        env: TOXENV=py35
      - python: 3.6
        env: TOXENV=py36
      - python: 3.7-dev
        env: TOXENV=py37
    install:
    - "pip install invoke"
    - "inv install"
    script:
    - "inv test"

  - stage: deploy
    python: 3.6
    before_install:
    - openssl aes-256-cbc -K $encrypted_2ef685e8f1b3_key -iv $encrypted_2ef685e8f1b3_iv
      -in .pypirc.enc -out .pypirc -d
    install: 
    - "pip install invoke"
    script:
    - "inv release"
